version: '3'
services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/changeme
      NEO4J_dbms_memory_heap_max__size: 8G
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - "7474:7474"
      - "7687:7687"
  splunk:
    image: splunk/splunk:latest
    hostname: splunkenterprise
    container_name: splunk
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_USER: splunk
      SPLUNK_PASSWORD: changeme
    ports:
      - "8000:8000"
      - "8089:8089"
