version: '3'
volumes:
  volume-neo-data:
  volume-splunk-etc:
  volume-splunk-var:
services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/changeme
      NEO4J_dbms_memory_heap_max__size: 8G
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - volume-neo-data:/data
  splunk:
    image: splunk/splunk:latest
    hostname: splunkenterprise
    container_name: splunk
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_USER: splunk
      SPLUNK_PASSWORD: changeme
    ports:
      - 8001:8000
    volumes:
      - volume-splunk-etc:/opt/splunk/etc
      - volume-splunk-var:/opt/splunk/var
      - ../apps/neo4s:/opt/splunk/etc/apps/neo4s
